/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "address")
public class Address implements Serializable {

    @Column(name = "AddressId", table = "address", nullable = false)
    @Id
    @FormParam("addressId")
    private Integer addressId;

    @Column(name = "AddressLine", table = "address")
    @Basic
    @FormParam("addressLine")
    private String addressLine;

    @Column(name = "City", table = "address")
    @Basic
    @FormParam("city")
    private String city;

    @Column(name = "Country", table = "address")
    @Basic
    @FormParam("country")
    private String country;

    @Column(name = "PostalCode", table = "address")
    @Basic
    @FormParam("postalCode")
    private String postalCode;

    @Column(name = "ModifiedDate", table = "address")
    @Basic
    @FormParam("modifiedDate")
    private String modifiedDate;

    @OneToMany(targetEntity = Customer.class, mappedBy = "address1")
    private List<Customer> customers1;

    public Integer getAddressId() {
        return this.addressId;
    }

    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    public String getAddressLine() {
        return this.addressLine;
    }

    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public List<Customer> getCustomers1() {
        return this.customers1;
    }

    public void setCustomers1(List<Customer> customers1) {
        this.customers1 = customers1;
    }

}
