/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "customer")
public class Customer implements Serializable {

    @Column(name = "CustomerId", table = "customer", nullable = false)
    @Id
    @FormParam("customerId")
    private Integer customerId;

    @Column(name = "FirstName", table = "customer")
    @Basic
    @FormParam("firstName")
    private String firstName;

    @Column(name = "LastName", table = "customer")
    @Basic
    @FormParam("lastName")
    private String lastName;

    @Column(name = "Contact", table = "customer")
    @Basic
    @FormParam("contact")
    private String contact;

    @Column(name = "Email", table = "customer")
    @Basic
    @FormParam("email")
    private String email;

    @Column(name = "Phone", table = "customer")
    @Basic
    @FormParam("phone")
    private String phone;

    @ManyToOne(targetEntity = Address.class)
    private Address address1;

    @OneToMany(targetEntity = Statisticscollector.class, mappedBy = "customer1")
    private List<Statisticscollector> statisticscollectors1;

    @OneToMany(targetEntity = So.class, mappedBy = "customer1")
    private List<So> soes1;

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Address getAddress1() {
        return this.address1;
    }

    public void setAddress1(Address address1) {
        this.address1 = address1;
    }

    public List<Statisticscollector> getStatisticscollectors1() {
        return this.statisticscollectors1;
    }

    public void setStatisticscollectors1(List<Statisticscollector> statisticscollectors1) {
        this.statisticscollectors1 = statisticscollectors1;
    }

    public List<So> getSoes1() {
        return this.soes1;
    }

    public void setSoes1(List<So> soes1) {
        this.soes1 = soes1;
    }

}
