/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "groups")
public class Group1 implements Serializable {

    @Column(name = "GroupId", table = "groups", nullable = false)
    @Id
    @FormParam("groupId")
    private Integer groupId;

    @Column(name = "Name", table = "groups", nullable = false)
    @Basic(optional = false)
    @FormParam("name")
    private String name;

    @OneToMany(targetEntity = Itemgroup.class, mappedBy = "groups1")
    private List<Itemgroup> itemgroups1;

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Itemgroup> getItemgroups1() {
        return this.itemgroups1;
    }

    public void setItemgroups1(List<Itemgroup> itemgroups1) {
        this.itemgroups1 = itemgroups1;
    }

}
