/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "groups")
public class Group1 implements Serializable {

    @Column(name = "GroupId", table = "groups", nullable = false)
    @Id
    @FormParam("groupId")
    private Integer groupId;

    @Column(name = "Name", table = "groups", nullable = false)
    @Basic(optional = false)
    @FormParam("name")
    private String name;

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
