/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "itemgroup")
public class Itemgroup implements Serializable {

    @Column(name = "IGId", table = "itemgroup", nullable = false)
    @Id
    @FormParam("iGId")
    private Integer iGId;

    @ManyToOne(targetEntity = Group1.class)
    private Group1 group11;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

    public Integer getIGId() {
        return this.iGId;
    }

    public void setIGId(Integer iGId) {
        this.iGId = iGId;
    }

    public Group1 getGroup11() {
        return this.group11;
    }

    public void setGroup11(Group1 group11) {
        this.group11 = group11;
    }

    public Item getItem1() {
        return this.item1;
    }

    public void setItem1(Item item1) {
        this.item1 = item1;
    }

}
