/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "itemdiscount")
public class Itemdiscount implements Serializable {

    @Column(name = "IDid", table = "itemdiscount", nullable = false)
    @Id
    @FormParam("iDid")
    private Integer iDid;

    @ManyToOne(targetEntity = Discountrule.class)
    private Discountrule discountrule1;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

    public Integer getIDid() {
        return this.iDid;
    }

    public void setIDid(Integer iDid) {
        this.iDid = iDid;
    }

    public Discountrule getDiscountrule1() {
        return this.discountrule1;
    }

    public void setDiscountrule1(Discountrule discountrule1) {
        this.discountrule1 = discountrule1;
    }

    public Item getItem1() {
        return this.item1;
    }

    public void setItem1(Item item1) {
        this.item1 = item1;
    }

}
