/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "paymenttype")
public class Paymenttype implements Serializable {

    @Column(name = "PTId", table = "paymenttype", nullable = false)
    @Id
    @FormParam("pTId")
    private Integer pTId;

    @Column(name = "TypeName", table = "paymenttype")
    @Basic
    @FormParam("typeName")
    private String typeName;

    public Integer getPTId() {
        return this.pTId;
    }

    public void setPTId(Integer pTId) {
        this.pTId = pTId;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

}
