/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "paymenttype")
public class Paymenttype implements Serializable {

    @Column(name = "PTId", table = "paymenttype", nullable = false)
    @Id
    @FormParam("pTId")
    private Integer pTId;

    @Column(name = "TypeName", table = "paymenttype")
    @Basic
    @FormParam("typeName")
    private String typeName;

    @OneToMany(targetEntity = Payment.class, mappedBy = "paymenttype1")
    private List<Payment> payments1;

    public Integer getPTId() {
        return this.pTId;
    }

    public void setPTId(Integer pTId) {
        this.pTId = pTId;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public List<Payment> getPayments1() {
        return this.payments1;
    }

    public void setPayments1(List<Payment> payments1) {
        this.payments1 = payments1;
    }

}
