/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "payment")
public class Payment implements Serializable {

    @Column(name = "PaymentId", table = "payment", nullable = false)
    @Id
    @FormParam("paymentId")
    private Integer paymentId;

    @Column(name = "PaymentInfo", table = "payment")
    @Basic
    @FormParam("paymentInfo")
    private String paymentInfo;

    @ManyToOne(targetEntity = Paymenttype.class)
    private Paymenttype paymenttype1;

    @ManyToOne(targetEntity = Paymentbill.class)
    private Paymentbill paymentbill1;

    @ManyToOne(targetEntity = So.class)
    private So so1;

    public Integer getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public String getPaymentInfo() {
        return this.paymentInfo;
    }

    public void setPaymentInfo(String paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    public Paymenttype getPaymenttype1() {
        return this.paymenttype1;
    }

    public void setPaymenttype1(Paymenttype paymenttype1) {
        this.paymenttype1 = paymenttype1;
    }

    public Paymentbill getPaymentbill1() {
        return this.paymentbill1;
    }

    public void setPaymentbill1(Paymentbill paymentbill1) {
        this.paymentbill1 = paymentbill1;
    }

    public So getSo1() {
        return this.so1;
    }

    public void setSo1(So so1) {
        this.so1 = so1;
    }

}
