/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
public class ProductItems implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;

    @ManyToOne(targetEntity = Soproduct.class)
    private Soproduct soproduct1;

    @ManyToOne(targetEntity = Item.class)
    private Item item1;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Soproduct getSoproduct1() {
        return this.soproduct1;
    }

    public void setSoproduct1(Soproduct soproduct1) {
        this.soproduct1 = soproduct1;
    }

    public Item getItem1() {
        return this.item1;
    }

    public void setItem1(Item item1) {
        this.item1 = item1;
    }

}
