/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.*;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "role")
public class Role implements Serializable {

    @Column(name = "RoleId", table = "role", nullable = false)
    @Id
    @FormParam("roleId")
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Integer roleId;

    @Column(name = "Name", table = "role")
    @Basic
    @FormParam("name")
    private String name;

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
