/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "role")
public class Role implements Serializable {

    @Column(name = "RoleId", table = "role", nullable = false)
    @Id
    @FormParam("roleId")
    private Integer roleId;

    @Column(name = "Name", table = "role")
    @Basic
    @FormParam("name")
    private String name;

    @OneToMany(targetEntity = UserRole.class, mappedBy = "role1")
    private List<UserRole> userRoles1;

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<UserRole> getUserRoles1() {
        return this.userRoles1;
    }

    public void setUserRoles1(List<UserRole> userRoles1) {
        this.userRoles1 = userRoles1;
    }

}
