/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "so")
public class So implements Serializable {

    @Column(name = "SOId", table = "so", nullable = false)
    @Id
    @FormParam("sOId")
    private Integer sOId;

    @Column(name = "DateCreated", table = "so")
    @Basic
    @FormParam("dateCreated")
    private String dateCreated;

    @Column(name = "OrderDate", table = "so")
    @Basic
    @FormParam("orderDate")
    private String orderDate;

    @Column(name = "Status", table = "so")
    @Basic
    @FormParam("status")
    private String status;

    @Column(name = "SONumber", table = "so")
    @Basic
    @FormParam("sONumber")
    private String sONumber;

    @Column(name = "PurchaseOrderNumber", table = "so")
    @Basic
    @FormParam("purchaseOrderNumber")
    private String purchaseOrderNumber;

    @Column(name = "DateModified", table = "so")
    @Basic
    @FormParam("dateModified")
    private String dateModified;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer1;

    @ManyToOne(targetEntity = User.class)
    private User user1;

    @OneToMany(targetEntity = Payment.class, mappedBy = "so1")
    private List<Payment> payments1;

    @OneToMany(targetEntity = Soproduct.class, mappedBy = "so1")
    private List<Soproduct> soproducts1;

    public Integer getSOId() {
        return this.sOId;
    }

    public void setSOId(Integer sOId) {
        this.sOId = sOId;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSONumber() {
        return this.sONumber;
    }

    public void setSONumber(String sONumber) {
        this.sONumber = sONumber;
    }

    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }

    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    public String getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(String dateModified) {
        this.dateModified = dateModified;
    }

    public Customer getCustomer1() {
        return this.customer1;
    }

    public void setCustomer1(Customer customer1) {
        this.customer1 = customer1;
    }

    public User getUser1() {
        return this.user1;
    }

    public void setUser1(User user1) {
        this.user1 = user1;
    }

    public List<Payment> getPayments1() {
        return this.payments1;
    }

    public void setPayments1(List<Payment> payments1) {
        this.payments1 = payments1;
    }

    public List<Soproduct> getSoproducts1() {
        return this.soproducts1;
    }

    public void setSoproducts1(List<Soproduct> soproducts1) {
        this.soproducts1 = soproducts1;
    }

}
