/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "soproduct")
public class Soproduct implements Serializable {

    @Column(name = "SOPId", table = "soproduct", nullable = false)
    @Id
    @FormParam("sOPId")
    private Integer sOPId;

    @Column(name = "MP", table = "soproduct", precision = 12)
    @Basic
    @FormParam("mp")
    private Float mp;

    @Column(name = "OTP", table = "soproduct", precision = 12)
    @Basic
    @FormParam("otp")
    private Float otp;

    @ManyToOne(targetEntity = So.class)
    private So so1;

    public Integer getSOPId() {
        return this.sOPId;
    }

    public void setSOPId(Integer sOPId) {
        this.sOPId = sOPId;
    }

    public Float getMp() {
        return this.mp;
    }

    public void setMp(Float mp) {
        this.mp = mp;
    }

    public Float getOtp() {
        return this.otp;
    }

    public void setOtp(Float otp) {
        this.otp = otp;
    }

    public So getSo1() {
        return this.so1;
    }

    public void setSo1(So so1) {
        this.so1 = so1;
    }

}
