/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "statisticscollector")
public class Statisticscollector implements Serializable {

    @Column(name = "SCId", table = "statisticscollector", nullable = false)
    @Id
    @FormParam("sCId")
    private Integer sCId;

    @Column(name = "StatisticType", table = "statisticscollector")
    @Basic
    @FormParam("statisticType")
    private String statisticType;

    @Column(name = "StatisticsInfo", table = "statisticscollector")
    @Basic
    @FormParam("statisticsInfo")
    private String statisticsInfo;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer1;

    public Integer getSCId() {
        return this.sCId;
    }

    public void setSCId(Integer sCId) {
        this.sCId = sCId;
    }

    public String getStatisticType() {
        return this.statisticType;
    }

    public void setStatisticType(String statisticType) {
        this.statisticType = statisticType;
    }

    public String getStatisticsInfo() {
        return this.statisticsInfo;
    }

    public void setStatisticsInfo(String statisticsInfo) {
        this.statisticsInfo = statisticsInfo;
    }

    public Customer getCustomer1() {
        return this.customer1;
    }

    public void setCustomer1(Customer customer1) {
        this.customer1 = customer1;
    }

}
