/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "user")
public class User implements Serializable {

    @Column(name = "UserId", table = "user", nullable = false)
    @Id
    @FormParam("userId")
    private Integer userId;

    @Column(name = "Login", table = "user")
    @Basic
    @FormParam("login")
    private String login;

    @Column(name = "Password", table = "user")
    @Basic
    @FormParam("password")
    private String password;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
