/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject1;

import javax.persistence.*;
import javax.ws.rs.FormParam;
import java.io.Serializable;
import java.util.List;

/**
 * @author dzni0816
 */
@Entity
@Table(name = "user")
public class User implements Serializable {

    @Column(name = "UserId", table = "user", nullable = false)
    @Id
    @FormParam("userId")
    private Integer userId;

    @Column(name = "Login", table = "user")
    @Basic
    @FormParam("login")
    private String login;

    @Column(name = "Password", table = "user")
    @Basic
    @FormParam("password")
    private String password;

    @OneToMany(targetEntity = So.class, mappedBy = "user1")
    private List<So> soes1;

    @OneToMany(targetEntity = UserRole.class, mappedBy = "user1")
    private List<UserRole> userRoles1;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<So> getSoes1() {
        return this.soes1;
    }

    public void setSoes1(List<So> soes1) {
        this.soes1 = soes1;
    }

    public List<UserRole> getUserRoles1() {
        return this.userRoles1;
    }

    public void setUserRoles1(List<UserRole> userRoles1) {
        this.userRoles1 = userRoles1;
    }

}
