/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "customer")
public class Customer implements Serializable {

    @Column(name = "CustomerId", table = "customer", nullable = false)
    @Id
    @FormParam("customerId")
    private Integer customerId;

    @Column(name = "FirstName", table = "customer")
    @Basic
    @FormParam("firstName")
    private String firstName;

    @Column(name = "LastName", table = "customer")
    @Basic
    @FormParam("lastName")
    private String lastName;

    @Column(name = "Contact", table = "customer")
    @Basic
    @FormParam("contact")
    private String contact;

    @Column(name = "Email", table = "customer")
    @Basic
    @FormParam("email")
    private String email;

    @Column(name = "Phone", table = "customer")
    @Basic
    @FormParam("phone")
    private String phone;

    @ManyToOne(optional = false, targetEntity = Address.class)
    @JoinColumn(name = "ADDRESS", referencedColumnName = "ADDRESSID")
    private Address address;

    @OneToMany(targetEntity = Statisticscollector.class, mappedBy = "custonerId")
    private List<Statisticscollector> statisticscollectorCollection;

    @OneToMany(targetEntity = So.class, mappedBy = "customerId")
    private List<So> soCollection;

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public List<Statisticscollector> getStatisticscollectorCollection() {
        return this.statisticscollectorCollection;
    }

    public void setStatisticscollectorCollection(List<Statisticscollector> statisticscollectorCollection) {
        this.statisticscollectorCollection = statisticscollectorCollection;
    }

    public List<So> getSoCollection() {
        return this.soCollection;
    }

    public void setSoCollection(List<So> soCollection) {
        this.soCollection = soCollection;
    }

}
