/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "group")
public class Group1 implements Serializable {

    @Column(name = "GroupId", table = "group", nullable = false)
    @Id
    @FormParam("groupId")
    private Integer groupId;

    @Column(name = "Name", table = "group", nullable = false)
    @Basic
    @FormParam("name")
    private String name;

    @OneToMany(targetEntity = Itemgroup.class, mappedBy = "groupId")
    private List<Itemgroup> itemgroupCollection;

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Itemgroup> getItemgroupCollection() {
        return this.itemgroupCollection;
    }

    public void setItemgroupCollection(List<Itemgroup> itemgroupCollection) {
        this.itemgroupCollection = itemgroupCollection;
    }

}
