/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "itemgroup")
public class Itemgroup implements Serializable {

    @Column(name = "IGId", table = "itemgroup", nullable = false)
    @Id
    @FormParam("iGId")
    private Integer iGId;

    @ManyToOne(optional = false, targetEntity = Item.class)
    @JoinColumn(name = "IID", referencedColumnName = "ITEMID")
    private Item iid;

    @ManyToOne(optional = false, targetEntity = Group1.class)
    @JoinColumn(name = "GROUPID", referencedColumnName = "GROUPID")
    private Group1 groupId;

    public Integer getIGId() {
        return this.iGId;
    }

    public void setIGId(Integer iGId) {
        this.iGId = iGId;
    }

    public Item getIid() {
        return this.iid;
    }

    public void setIid(Item iid) {
        this.iid = iid;
    }

    public Group1 getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Group1 groupId) {
        this.groupId = groupId;
    }

}
