/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "paymenttype")
public class Paymenttype implements Serializable {

    @Column(name = "PTId", table = "paymenttype", nullable = false)
    @Id
    @FormParam("pTId")
    private Integer pTId;

    @Column(name = "TypeName", table = "paymenttype")
    @Basic
    @FormParam("typeName")
    private String typeName;

    @OneToMany(targetEntity = Payment.class, mappedBy = "pTId")
    private List<Payment> paymentCollection;

    public Integer getPTId() {
        return this.pTId;
    }

    public void setPTId(Integer pTId) {
        this.pTId = pTId;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public List<Payment> getPaymentCollection() {
        return this.paymentCollection;
    }

    public void setPaymentCollection(List<Payment> paymentCollection) {
        this.paymentCollection = paymentCollection;
    }

}
