/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "payment")
public class Payment implements Serializable {

    @Column(name = "PaymentId", table = "payment", nullable = false)
    @Id
    @FormParam("paymentId")
    private Integer paymentId;

    @Column(name = "PaymentInfo", table = "payment")
    @Basic
    @FormParam("paymentInfo")
    private String paymentInfo;

    @ManyToOne(optional = false, targetEntity = So.class)
    @JoinColumn(name = "SOID", referencedColumnName = "SOID")
    private So sOId;

    @ManyToOne(optional = false, targetEntity = Paymenttype.class)
    @JoinColumn(name = "PTID", referencedColumnName = "PTID")
    private Paymenttype pTId;

    @ManyToOne(optional = false, targetEntity = Paymentbill.class)
    @JoinColumn(name = "PBID", referencedColumnName = "PBID")
    private Paymentbill pBId;

    public Integer getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public String getPaymentInfo() {
        return this.paymentInfo;
    }

    public void setPaymentInfo(String paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    public So getSOId() {
        return this.sOId;
    }

    public void setSOId(So sOId) {
        this.sOId = sOId;
    }

    public Paymenttype getPTId() {
        return this.pTId;
    }

    public void setPTId(Paymenttype pTId) {
        this.pTId = pTId;
    }

    public Paymentbill getPBId() {
        return this.pBId;
    }

    public void setPBId(Paymentbill pBId) {
        this.pBId = pBId;
    }

}
