/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "role")
public class Role implements Serializable {

    @Column(name = "RoleId", table = "role", nullable = false)
    @Id
    @FormParam("roleId")
    private Integer roleId;

    @Column(name = "Name", table = "role")
    @Basic
    @FormParam("name")
    private String name;

    @ManyToMany(targetEntity = User.class)
    @JoinTable(name = "userrole", joinColumns = {
        @JoinColumn(name = "ROLEID", referencedColumnName = "ROLEID")}, inverseJoinColumns = {
        @JoinColumn(name = "USERID", referencedColumnName = "USERID")})
    private List<User> userCollection;

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<User> getUserCollection() {
        return this.userCollection;
    }

    public void setUserCollection(List<User> userCollection) {
        this.userCollection = userCollection;
    }

}
