/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "so")
public class So implements Serializable {

    @Column(name = "SOId", table = "so", nullable = false)
    @Id
    @FormParam("sOId")
    private Integer sOId;

    @Column(name = "DateCreated", table = "so")
    @Basic
    @FormParam("dateCreated")
    private String dateCreated;

    @Column(name = "OrderDate", table = "so")
    @Basic
    @FormParam("orderDate")
    private String orderDate;

    @Column(name = "Status", table = "so")
    @Basic
    @FormParam("status")
    private String status;

    @Column(name = "SONumber", table = "so")
    @Basic
    @FormParam("sONumber")
    private String sONumber;

    @Column(name = "PurchaseOrderNumber", table = "so")
    @Basic
    @FormParam("purchaseOrderNumber")
    private String purchaseOrderNumber;

    @Column(name = "DateModified", table = "so")
    @Basic
    @FormParam("dateModified")
    private String dateModified;

    @OneToOne(targetEntity = Soproduct.class)
    private Soproduct soproduct;

    @ManyToOne(targetEntity = Customer.class)
    @JoinColumn(name = "CUSTOMERID", referencedColumnName = "CUSTOMERID")
    private Customer customerId;

    @ManyToOne(optional = false, targetEntity = User.class)
    @JoinColumn(name = "USERID", referencedColumnName = "USERID")
    private User userID;

    @OneToMany(targetEntity = Payment.class, mappedBy = "sOId")
    private List<Payment> paymentCollection;

    public Integer getSOId() {
        return this.sOId;
    }

    public void setSOId(Integer sOId) {
        this.sOId = sOId;
    }

    public String getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSONumber() {
        return this.sONumber;
    }

    public void setSONumber(String sONumber) {
        this.sONumber = sONumber;
    }

    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }

    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }

    public String getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(String dateModified) {
        this.dateModified = dateModified;
    }

    public Soproduct getSoproduct() {
        return this.soproduct;
    }

    public void setSoproduct(Soproduct soproduct) {
        this.soproduct = soproduct;
    }

    public Customer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Customer customerId) {
        this.customerId = customerId;
    }

    public User getUserID() {
        return this.userID;
    }

    public void setUserID(User userID) {
        this.userID = userID;
    }

    public List<Payment> getPaymentCollection() {
        return this.paymentCollection;
    }

    public void setPaymentCollection(List<Payment> paymentCollection) {
        this.paymentCollection = paymentCollection;
    }

}
