/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "soproduct")
public class Soproduct implements Serializable {

    @Column(name = "SOPId", table = "soproduct", nullable = false)
    @Id
    @FormParam("sOPId")
    private Integer sOPId;

    @Column(name = "MP", table = "soproduct", precision = 12)
    @Basic
    @FormParam("mp")
    private Float mp;

    @Column(name = "OTP", table = "soproduct", precision = 12)
    @Basic
    @FormParam("otp")
    private Float otp;

    @OneToOne(optional = false, targetEntity = So.class, mappedBy = "soproduct")
    @JoinColumn(name = "SOPID", referencedColumnName = "SOID", insertable = false, updatable = false)
    private So so;

    @ManyToOne(optional = false, targetEntity = Item.class)
    @JoinColumn(name = "ITEMID", referencedColumnName = "ITEMID")
    private Item itemId;

    public Integer getSOPId() {
        return this.sOPId;
    }

    public void setSOPId(Integer sOPId) {
        this.sOPId = sOPId;
    }

    public Float getMp() {
        return this.mp;
    }

    public void setMp(Float mp) {
        this.mp = mp;
    }

    public Float getOtp() {
        return this.otp;
    }

    public void setOtp(Float otp) {
        this.otp = otp;
    }

    public So getSo() {
        return this.so;
    }

    public void setSo(So so) {
        this.so = so;
    }

    public Item getItemId() {
        return this.itemId;
    }

    public void setItemId(Item itemId) {
        this.itemId = itemId;
    }

}
