/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "statisticscollector")
public class Statisticscollector implements Serializable {

    @Column(name = "SCId", table = "statisticscollector", nullable = false)
    @Id
    @FormParam("sCId")
    private Integer sCId;

    @Column(name = "StatisticType", table = "statisticscollector")
    @Basic
    @FormParam("statisticType")
    private String statisticType;

    @Column(name = "StatisticsInfo", table = "statisticscollector")
    @Basic
    @FormParam("statisticsInfo")
    private String statisticsInfo;

    @ManyToOne(optional = false, targetEntity = Customer.class)
    @JoinColumn(name = "CUSTONERID", referencedColumnName = "CUSTOMERID")
    private Customer custonerId;

    public Integer getSCId() {
        return this.sCId;
    }

    public void setSCId(Integer sCId) {
        this.sCId = sCId;
    }

    public String getStatisticType() {
        return this.statisticType;
    }

    public void setStatisticType(String statisticType) {
        this.statisticType = statisticType;
    }

    public String getStatisticsInfo() {
        return this.statisticsInfo;
    }

    public void setStatisticsInfo(String statisticsInfo) {
        this.statisticsInfo = statisticsInfo;
    }

    public Customer getCustonerId() {
        return this.custonerId;
    }

    public void setCustonerId(Customer custonerId) {
        this.custonerId = custonerId;
    }

}
