/**
 * This file was generated by the JPA Modeler
 */
package com.mycompany.mavenproject3;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.FormParam;

/**
 * @author Admin
 */
@Entity
@Table(name = "user")
public class User implements Serializable {

    @Column(name = "UserId", table = "user", nullable = false)
    @Id
    @FormParam("userId")
    private Integer userId;

    @Column(name = "Login", table = "user")
    @Basic
    @FormParam("login")
    private String login;

    @Column(name = "Password", table = "user")
    @Basic
    @FormParam("password")
    private String password;

    @OneToMany(targetEntity = So.class, mappedBy = "userID")
    private List<So> soCollection;

    @ManyToMany(targetEntity = Role.class, mappedBy = "userCollection")
    private List<Role> roleCollection;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<So> getSoCollection() {
        return this.soCollection;
    }

    public void setSoCollection(List<So> soCollection) {
        this.soCollection = soCollection;
    }

    public List<Role> getRoleCollection() {
        return this.roleCollection;
    }

    public void setRoleCollection(List<Role> roleCollection) {
        this.roleCollection = roleCollection;
    }

}
